### PR TITLE
added GUI; Need to add status updates

### PR DESCRIPTION
**Pull request by jmkim2392**

### CODE REVIEW

**Comment by jmkim2392** [comment]
Some buttons will require logic to finalize the GUI

**Comment by jmkim2392** [comment]
This is just for reference, please don't merge as i will be doing additional work on it.

**Comment by jmkim2392** [comment]
I've added the status messages to be displayed and have it integrated with FTP.
Ready to be reviewed and merged into dev

**Review by isheik — COMMENTED** [review]
Looks good to me

**Pull request merged**
